## https://taplo.tamasfe.dev/configuration/file.html
exclude = ["target/**"]

[formatting]
column_width  = 120
align_entries = true
crlf          = false

[[rule]]
keys       = ["workspace.dependencies", "dependencies", "dev-dependencies", "build-dependencies"]
formatting = { reorder_keys = true }